version: '3.7'
services:
  dns_server:
    images: "bind9"
    ports: 
      - "53:53"
    networks:
      - webserver 
    volumes:
      - ./
  proxy_server:
    images: "nginx"
    ports: 
      - "8800:80"
    networks: 
      - webserver 
    volumes:
      - ./proxy_server/conf.d/reverse_proxy.conf:/etc/nginx/conf.d/reverse_proxy.conf
      - ./proxy_server/html:/usr/share/nginx/html
  srv1: 
    images: "nginx"
    ports: 
      - "8801:80"
    networks:
      - webserver 
    volumes:
      - ./srv1/html:/usr/share/nginx/html
  srv2:
    images: "nginx"
    ports:
      - "8802:80"
    networks:
      - webserver
    volumes:
      - ./srv2/html:/usr/share/nginx/html
  srv3:
    images: "nginx"
    ports:
      - "8803:80"
    networks:
      - webserver
    volumes:
      - ./srv3/html:/usr/share/nginx/html
networks: #要使用自訂網路需先定義一個與services同級的networks 
  webserver:
    external: true 